### ISSUE TITLE
Create safe limitations on Datadog API calls

### ISSUE THREAD

**Issue by myui** [takuti/datadog-anomaly-detector#13]
datadog-anomaly-detector SHOULD have a safe limitation on Datadog API calls per hour.
https://help.datadoghq.com/hc/en-us/articles/205060139-API-rate-limit

The limit is better to be configurable.
Also, warning messages are going to be reported on Slack channel similar to other errors.

**Comment by takuti** [comment]
@myui Thanks!

The following lines check if the limit is reachable: https://github.com/takuti/datadog-anomaly-detector/blob/master/daemonizer.py#L29-L31

Are there any other requests you meant? And, what does the "configurable" limit indicate?

**Comment by myui** [comment]
@takuti `sys.exit(1)`!? It's not a good behavior for daemon. It should just write WARNING messages to log and Slack channel.

I meant `300` should be configurable in INI file.

Other service might use API calls. So, datadog-anomaly-detector could use 200-300.
Also, Datadog's 300 limits might be change over time.

**Comment by takuti** [comment]
@myui IMO, `sys.exit(1)` (i.e. explicitly fail to launch a daemon) is important behavior because reaching API rate limit is highly dangerous in case that other services outside of datadog-anomaly-detector are using the API; they may be stopped suddenly.

What a daemon does is:
1. Log an error message
2. Notify it to a Slack channel
3. Stop launching a daemon (`sys.exit(1)`)

OK, understood what "configurable" indicates.

**Comment by takuti** [comment]
@myui Removed `sys.exit(1)` and aggregated all exception handling to the daemon script: https://github.com/takuti/datadog-anomaly-detector/blob/c9724532e734a56ef21a1e14b922c6f746dad787/daemonizer.py#L46-L69

When any kinds of exceptions (e.g. DD API related) are raised, a daemon safely transfers to an idling state; it sleeps for 1 hour w/ notifying to Slack/logfile.
